# Creating an array

In [2]:
import numpy as np

In [6]:
# create a 1-D array
m=np.array(np.arange(5))

In [7]:
m.dtype

dtype('int64')

In [9]:
m

array([0, 1, 2, 3, 4])

In [11]:
# check its shape
m.shape

(5,)

In [15]:
#create a 2D array
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
n=np.array([np.arange(4), np.arange(4)])
n

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [25]:
# create a 3D array
a3=np.array([[np.arange(0,5),np.arange(5,10)],[np.arange(10,15),np.arange(15,20)]])
print(a3)
print(a3.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
(2, 2, 5)


In [26]:
# create an array with random data
r=np.random.randn(2,3)
r

array([[-0.10981389,  0.73330203,  1.79577412],
       [ 0.52609747,  0.96143443, -1.21434326]])

# Slicing

In [30]:
# select an element from an array
a3[1, 1, 4]

19

In [32]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [33]:
a[:7:2]

array([0, 2, 4, 6])

In [35]:
# slice a 2-D array
a2=np.array([np.arange(9),np.arange(9)])
a2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [36]:
a2[0:1, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [41]:
a2[:, 3:8]

array([[3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7]])

In [42]:
a2[:,::2]

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [43]:
a2[:,::-1]

array([[8, 7, 6, 5, 4, 3, 2, 1, 0],
       [8, 7, 6, 5, 4, 3, 2, 1, 0]])

In [48]:
# slice 3D array
a3 = np.random.randn(2,3,4)
a3

array([[[-0.12945056,  0.40444222,  0.4630022 , -0.32226983],
        [ 1.44238962,  1.8651124 , -0.44293879, -0.36246807],
        [-0.59300122, -0.21055245, -0.79366648,  1.29253082]],

       [[ 0.90499557,  1.21680285,  1.44688441,  0.09196464],
        [ 0.21641276,  2.2490262 , -0.73617329, -1.83970365],
        [-0.76988072, -1.59279406,  0.41900446,  0.91610123]]])

In [49]:
a3[0,0:2,0:2]

array([[-0.12945056,  0.40444222],
       [ 1.44238962,  1.8651124 ]])

In [51]:
# Compare a copied array and a non-copied array
arr_slice=a[5:8]
arr_slice[1]=12345
a

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8])

In [53]:
arr_slice=a[5:8].copy()
arr_slice[1]=1234567
a

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8])

# Munipulating array shapes

In [54]:
# Manipulate array shapes
b=np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
# change the array into multi-dimensional one
b.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
# change b back to 1 dimensional
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
# transpose an array
b.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
c=b.reshape(6,4)

In [65]:
c.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [67]:
# resize(), different from reshape(), it changes the array directly
b.resize(3,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

# Stacking and Splitting

In [68]:
# stack the arrays
a=np.arange(9).reshape(3,3)
b=2*a

In [69]:
# horizontal stacking
c=np.hstack((a, b)) 

In [70]:
c

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [71]:
np.hsplit(c,3)

[array([[0, 1],
        [3, 4],
        [6, 7]]),
 array([[ 2,  0],
        [ 5,  6],
        [ 8, 12]]),
 array([[ 2,  4],
        [ 8, 10],
        [14, 16]])]

# Boolean Indexing

In [72]:
# Boolean Indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [73]:
data = np.random.randn(7, 4)
data

array([[-0.53248487,  0.13357955,  1.16160387,  1.68678308],
       [-1.86398057, -0.66707389,  1.22427361, -1.16370665],
       [-1.58736213, -1.63586546,  0.57307095, -0.19528969],
       [-0.26638709, -0.20005804, -0.93424058,  0.43808295],
       [-0.08911205, -1.66190413,  0.32350497,  1.85384242],
       [-1.00694535,  0.21869683,  0.02632413,  1.37660699],
       [-0.11664465, -0.86388787,  1.78912316, -0.84501033]])

In [75]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [76]:
data[names == 'Bob']

array([[-0.53248487,  0.13357955,  1.16160387,  1.68678308],
       [-0.26638709, -0.20005804, -0.93424058,  0.43808295]])

In [77]:
# select the columns
data[names == 'Bob', 3]

array([1.68678308, 0.43808295])

In [78]:
# select all other rows excluding Bob
data[~(names == 'Bob')]

array([[-1.86398057, -0.66707389,  1.22427361, -1.16370665],
       [-1.58736213, -1.63586546,  0.57307095, -0.19528969],
       [-0.08911205, -1.66190413,  0.32350497,  1.85384242],
       [-1.00694535,  0.21869683,  0.02632413,  1.37660699],
       [-0.11664465, -0.86388787,  1.78912316, -0.84501033]])

# Sorting

In [81]:
# sort an array
arr = np.random.randn(6)
arr.sort()
arr

array([-1.73284538,  0.32763671,  0.45920443,  0.70164212,  1.08745085,
        1.60055535])

In [82]:
# sort in descending order
arr[::-1]

array([ 1.60055535,  1.08745085,  0.70164212,  0.45920443,  0.32763671,
       -1.73284538])

In [83]:
# sort multi-dimensional arrays
x = np.random.randn(5, 3)

In [84]:
x

array([[ 1.19604093, -1.39185879, -0.09543442],
       [ 2.31434445,  0.52001538, -1.42968581],
       [-0.04010355, -0.67509608, -0.19616876],
       [ 1.97786467,  0.53700681,  0.15521452],
       [ 0.96659479, -0.47749474,  1.27070781]])

In [86]:
x.sort(0)
x

array([[-0.04010355, -1.39185879, -1.42968581],
       [ 0.96659479, -0.67509608, -0.19616876],
       [ 1.19604093, -0.47749474, -0.09543442],
       [ 1.97786467,  0.52001538,  0.15521452],
       [ 2.31434445,  0.53700681,  1.27070781]])

In [128]:
x

array([[-0.58061914, -0.67510465, -0.5318933 ],
       [-0.17197433, -0.66241972, -0.21307814],
       [-0.05104839, -0.17559099,  0.09563719],
       [ 0.23884671,  0.21495166,  0.369866  ],
       [ 2.00022268,  1.11949093,  0.38472819]])

# Calculations

In [5]:
m = np.arange(10)
n = np.arange(10, 20)
print('m', m)
print('n', n)
print('m+n', m+n)  
# instead of having to use a loop when working with a list, you can directly add two arrays

m [0 1 2 3 4 5 6 7 8 9]
n [10 11 12 13 14 15 16 17 18 19]
m+n [10 12 14 16 18 20 22 24 26 28]


In [9]:
# broadcasting
m = np.random.randint(0, 100, (2, 4))
n = 1
print('m', m)
print('m+n', m+n)  

m [[12 88 25 22]
 [45 73 63 46]]
m+n [[13 89 26 23]
 [46 74 64 47]]


In [11]:
print('sum of all elements', m.sum())
print('sum the rows', m.sum(axis = 0))
print('sum the columns', m.sum(axis = 1))

sum of all elements 374
sum the rows [ 57 161  88  68]
sum the columns [147 227]


In [14]:
A = np.array([[6, 7],
              [8, 9]])

B = np.array([[1, 3],
              [5, 7]])
print('Matrix multiplication \n' , np.dot(A, B))
print('Element-wise multiplication\n', np.multiply(A, B))

Matrix multiplication 
 [[41 67]
 [53 87]]
Element-wise multiplication
 [[ 6 21]
 [40 63]]
