# Writing CSV files with NumPy

In [63]:
import numpy as np
np.random.seed(42)
a = np.random.randn(3, 4)

In [64]:
print(a)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]


In [65]:
a[2][2] = np.nan # set a nan value

In [66]:
np.savetxt('np.csv', a, fmt='%.2f', delimiter=',', header=" #1, #2, #3, #4") 

In [67]:
cat np.csv #read the file to check it

#  #1, #2, #3, #4
0.50,-0.14,0.65,1.52
-0.23,-0.23,1.58,0.77
-0.47,0.54,nan,-0.47


# Writing CSV files with Pandas

In [68]:
import pandas as pd

In [69]:
df = pd.DataFrame(a)
print(df)

          0         1         2         3
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560       NaN -0.465730


In [70]:
df.to_csv('pd.csv', float_format='%.2f', na_rep="NAN!")

# Reading and writing to Excel

In [71]:
filename="excel_demo.xlsx"
df.to_excel(filename, sheet_name='Random Data')

In [72]:
print(pd.read_excel(filename, 'Random Data'))

   Unnamed: 0         0         1         2         3
0           0  0.496714 -0.138264  0.647689  1.523030
1           1 -0.234153 -0.234137  1.579213  0.767435
2           2 -0.469474  0.542560       NaN -0.465730


# JASON Data

In [73]:
import json

In [74]:
json_str ='{"country":"Netherlands","dma_code":"0","timezone":"Europe\/Amsterdam","area_code":"0","ip":"46.19.37.108","asn":"AS196752","continent_code":"EU","isp":"TilaaV.O.F.","longitude":5.75,"latitude":52.5,"country_code":"NL","country_code3":"NLD"}'

In [75]:
data = json.loads(json_str)

In [76]:
print("Country", data["country"]) # fetch the value

Country Netherlands


In [77]:
data["country"] = "Brazil"  # change the value

In [78]:
print(json.dumps(data)) # create a string from the new JSON data:

{"country": "Brazil", "dma_code": "0", "timezone": "Europe/Amsterdam", "area_code": "0", "ip": "46.19.37.108", "asn": "AS196752", "continent_code": "EU", "isp": "TilaaV.O.F.", "longitude": 5.75, "latitude": 52.5, "country_code": "NL", "country_code3": "NLD"}


### Read Json data with Pandas

In [79]:
data2 = pd.read_json(json_str, typ='series')
print("Series\n", data2)

Series
 country                Netherlands
dma_code                         0
timezone          Europe/Amsterdam
area_code                        0
ip                    46.19.37.108
asn                       AS196752
continent_code                  EU
isp                    TilaaV.O.F.
longitude                     5.75
latitude                      52.5
country_code                    NL
country_code3                  NLD
dtype: object


In [80]:
data2["country"] = "China"   # change the value
print("New Series\n", data2.to_json())

New Series
 {"country":"China","dma_code":"0","timezone":"Europe\/Amsterdam","area_code":"0","ip":"46.19.37.108","asn":"AS196752","continent_code":"EU","isp":"TilaaV.O.F.","longitude":5.75,"latitude":52.5,"country_code":"NL","country_code3":"NLD"}


# Real-world Example with JSON Data

In [82]:
import json
import requests
import pandas as pd

request data

In [83]:
response = requests.get("https://jsonplaceholder.typicode.com/todos")
todos = json.loads(response.text)

In [84]:
type(todos)

list

In [85]:
todos[:10]

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False},
 {'userId': 1,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'completed': False},
 {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False},
 {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True},
 {'userId': 1,
  'id': 5,
  'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum',
  'completed': False},
 {'userId': 1,
  'id': 6,
  'title': 'qui ullam ratione quibusdam voluptatem quia omnis',
  'completed': False},
 {'userId': 1,
  'id': 7,
  'title': 'illo expedita consequatur quia in',
  'completed': False},
 {'userId': 1,
  'id': 8,
  'title': 'quo adipisci enim quam ut ab',
  'completed': True},
 {'userId': 1,
  'id': 9,
  'title': 'molestiae perspiciatis ipsa',
  'completed': False},
 {'userId': 1,
  'id': 10,
  'title': 'illo est ratione doloremque quia maiores aut',
  'completed': True}]

In [88]:
df = pd.DataFrame.from_dict(todos) # convert the data into a Pandas DataFrame
print(df.shape)

(200, 4)


In [89]:
print(df.head(10))

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False
5       1   6  qui ullam ratione quibusdam voluptatem quia omnis      False
6       1   7                  illo expedita consequatur quia in      False
7       1   8                       quo adipisci enim quam ut ab       True
8       1   9                        molestiae perspiciatis ipsa      False
9       1  10       illo est ratione doloremque quia maiores aut       True


In [9]:
print(df.dtypes)  # Check whether the data types are correct

userId        int64
id            int64
title        object
completed      bool
dtype: object


In [11]:
# Use pivot_table to analyse the data:  how many tasks did each user complete?
df_byuser = pd.pivot_table(df, index = 'userId', values = 'completed', aggfunc = 'sum')

In [13]:
print(df_byuser.sort_values(by = ['completed',], ascending = False))

        completed
userId           
5              12
10             12
1              11
8              11
7               9
2               8
9               8
3               7
4               6
6               6


# Webscraping

In [90]:
from bs4 import BeautifulSoup as bs #load the libraries
import requests    

In [94]:
# download the html from the webpage
URL = 'https://quotes.toscrape.com/page/1/'
  
req = requests.get(URL)
soup = bs(req.text, 'html.parser')
print(soup.prettify())    # you can use soup.prettify() to display it in a better format

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Quotes to Scrape
  </title>
  <link href="/static/bootstrap.min.css" rel="stylesheet"/>
  <link href="/static/main.css" rel="stylesheet"/>
 </head>
 <body>
  <div class="container">
   <div class="row header-box">
    <div class="col-md-8">
     <h1>
      <a href="/" style="text-decoration: none">
       Quotes to Scrape
      </a>
     </h1>
    </div>
    <div class="col-md-4">
     <p>
      <a href="/login">
       Login
      </a>
     </p>
    </div>
   </div>
   <div class="row">
    <div class="col-md-8">
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert

In [95]:
quotes = soup.find_all('span',attrs = {'class':'text'}) 
quote_list = []
for quote in quotes:
    quote_list.append(quote.text)

In [99]:
authors = soup.find_all('small', attrs = {'class': 'author'})
df_quoteauthor = pd.DataFrame(columns = ['quote', 'authors']) # create an empty DataFrame
for quote, author in zip(quotes, authors):   # use a loop to save both quotes and authors into the DataFrame
    df_quoteauthor.loc[len(df_quoteauthor)] = [quote.text, author.text]

In [101]:
print(df_quoteauthor.head(10))
print(df_quotes.shape)

                                               quote            authors
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin
(10, 2)


In [102]:
## We will reuse the above the code and use a for loop to scrape data from multiple webpages. 


URL = 'https://quotes.toscrape.com/page/'
df_quoteauthor = pd.DataFrame(columns = ['quote', 'authors']) # create an empty DataFrame  

for page in range(1, 11):
    req = requests.get(URL + str(page))
    soup = bs(req.text, 'html.parser')
    
    quotes = soup.find_all('span',attrs = {'class':'text'}) 
    authors = soup.find_all('small', attrs = {'class': 'author'})

    for quote, author in zip(quotes, authors):   # use a loop to save both quotes and authors into the DataFrame
        df_quoteauthor.loc[len(df_quoteauthor)] = [quote.text, author.text]

print(df_quoteauthor.head(10))
print(df_quoteauthor.shape)

                                               quote            authors
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin
(100, 2)
